name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: publish SharpLogContext on version change
      id: publish_nuget_1
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: SharpLogContext/SharpLogContext.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        NO_BUILD: true
    - name: publish SharpLogContext.MassTransit on version change
      id: publish_nuget_2
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: SharpLogContext.MassTransit/SharpLogContext.MassTransit.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        NO_BUILD: true
    - name: publish SharpLogContext.NetCore on version change
      id: publish_nuget_3
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: SharpLogContext.NetCore/SharpLogContext.NetCore.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        NO_BUILD: true